### ISSUE TITLE
finished

### ISSUE THREAD

**Issue by thibaultChatelain** [PolytechLyon/2019-isi3-graph-chatelain-bruhat#1]

**Comment by Slashgear** [comment]
⚠️ ne pas toucher à mes commentaires

- [ ] Vous avez ouvert votre fichier sur Github, ce n'est pas lisible... Un souci d'encodage https://github.com/PolytechLyon/2019-isi3-graph-chatelain-bruhat/blob/master/RAPPORT.md

- [ ] Les fichiers eclipse ne doivent pas être commit dans le repot

- [ ] Certains paramètres de fonction possèdent un `_` ? Pourquoi ? Estce utile ? autant l'utiliser partout ou ne pas l'utiliser du tout

- [ ] Connaissez vous la différence entre une List et un Set en Java ?

https://github.com/PolytechLyon/2019-isi3-graph-chatelain-bruhat/blob/2a926d49131faafa61eba0ec580411e728ce0530/src/main/java/graph/Graph.java#L50-L52

Ici devrait on utiliser un Set ou une List ? Justififer

- [ ] Ne trouvez vous pas que les deux parcours se ressemblent énormément dans leur algo ?

- [ ] A quoi vous sert cette fonction ? 

https://github.com/PolytechLyon/2019-isi3-graph-chatelain-bruhat/blob/2a926d49131faafa61eba0ec580411e728ce0530/src/main/java/graph/GraphIterator.java#L18

Prévenez moi quand vous avez pris les retours.

**Comment by thibaultChatelain** [comment]
- L'encodage est corrigé pour le rapport
- les fichiers eclipse ont été supprimés
- les paramètres comportant un "_" ont été enlevés: il s'agit d'une convention venant du C où il était nécessaire d'avoir des paramètres de fonctions différents des attributs de classe pour pouvoir compiler, elle est donc inutile ici
- la différence entre une List et un Set est expliquée dans le rapport (un Set est une liste qui ne contient aucun élément null ni aucun doublon)
- les deux parcours se ressemblent et sont désormais effectués à partir d'une méthode de la classe mère GraphIterator
- la fonction getFirst permet de renvoyer le premier élément de la collection sur laquelle on itère, dans notre cas elle n'est pas absolument nécessaire puisque le premier noeud du graphe est celui que l'on donne lors de la création de l'itérateur

**Comment by Slashgear** [comment]
Ok great 👍 

Beaucoup de "cast magic tricks" dans vos BFS DFS, je pense qu'on pourrait voir ensemble pour quelque chose de plus simple. Si vous êtes curieux, je vous monterai ça au prochain TP.

Sinon TP fini
